version: '3.7'
services:
  traefik:
    image: traefik:chevrotin
    restart: unless-stopped
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./conf/traefik.toml:/traefik.toml
      - ./conf/acme.json:/acme.json
    networks:
      - oueb
  
  grafana:
    image: grafana/grafana:6.6.0
    container_name: grafana
    restart: "unless-stopped"
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.grafana-redirect-secure.redirectscheme.scheme=https
      - traefik.http.routers.grafana-insecure.middlewares=grafana-redirect-secure
      - traefik.http.routers.grafana-insecure.rule=Host(`grafana.localhost.fr`)
      - traefik.http.routers.grafana-insecure.entrypoints=insecure
      - traefik.http.routers.grafana-secure.rule=Host(`grafana.localhost.fr`)
      - traefik.http.routers.grafana-secure.tls.certresolver=mytlschallenge
      - traefik.http.routers.grafana-secure.tls=true
      - traefik.http.routers.grafana-secure.entrypoints=secure
      - traefik.http.services.grafana-secure.loadbalancer.server.port=3000
    networks:
      - oueb
      
networks:
  oueb:
    driver: bridge